{
 "title": "Application Health & Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"fpe-tools-stg\",  e2_cluster=\"uls-stg01\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod ready status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(kube_pod_container_status_ready{job=\"kube-state-metrics\",namespace=~\"fpe-tools-(stg)\", pod=~\"$pod\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crash Back loop",
   "type": "timeseries",
   "description": "Value will be 1 if a pod is in crah back loop for more than 1 minute",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max_over_time(kube_pod_container_status_waiting_reason{job=\"kube-state-metrics\", pod =~\"$pod\", namespace=~\"fpe-tools-(stg)\",reason=\"CrashLoopBackOff\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarting Pods (5m)",
   "type": "timeseries",
   "description": "Checks how many times the selected dashboards are restarting in 5 minutes interval",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"fpe-tools-(stg)\", pod=~ \"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage GB (WSS)",
   "type": "timeseries",
   "description": "WSS means working set size.\nThe container's Working Set Size (WSS) — the memory actively being used and not reclaimable.\nExcludes cache and pages that can be reclaimed under memory pressure.\nUSE CASE:\nA better metric for understanding how much memory your app truly needs.\nGood for sizing and scaling decisions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(sum by (pod, container) (container_memory_working_set_bytes{container!=\"\",pod=~\"$pod\", namespace=~\"fpe-tools-(stg)\"}))/ (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage Memory utilization(WSS)",
   "type": "timeseries",
   "description": "Memory Usage (WSS)/ Memory Limit ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "100 * (sum by (pod, container) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"\", container!~\"POD\"} ) / sum by (pod, container) (container_spec_memory_limit_bytes{pod=~\"$pod\", container!=\"\", container!~\"POD\"} ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage(GB)",
   "type": "timeseries",
   "description": "Total memory used by the container, including cache, buffers, and unreclaimable memory.\nIncludes inactive and cache pages.\nUSE CASES:\nUseful for understanding the total memory footprint of a container.\nCan be misleading if most of the memory is cache that can be reclaimed.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (container, pod) (container_memory_usage_bytes{container!=\"\",pod=~\"$pod\", namespace=~\"fpe-tools-(stg)\"})/ (1024 * 1024 * 1024)"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{container!=\"\", pod=~\"$pod\", namespace=\"fpe-tools-stg\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Running Pods",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"fpe-tools-(stg)\"})"
    }
   ]
  },
  {
   "title": "App Uptime (hours)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((time() -(process_start_time_seconds{namespace=\"fpe-tools-stg\", pod =~\"$pod\"})) / 3600)\r\n"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}