{
 "title": "Kafka Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_total_messagesinpersec_count{namespace=\"fpe-tools-stg\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Received Per second",
   "type": "timeseries",
   "description": "Counter that tracks the cumulative number of messages received per second.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_brokertopicmetrics_total_messagesinpersec_count{namespace=\"fpe-tools-stg\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes out per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{namespace=\"fpe-tools-stg\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bite in per sec",
   "type": "timeseries",
   "description": "Bite in per sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": " sum by (instance)(rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{namespace=\"fpe-tools-stg\", instance=~\"$instance\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Controller count",
   "type": "timeseries",
   "description": "In a Kafka cluster, one of the brokers is elected as the controller. This metric shows whether the current broker is the active controller.\nValue is 1 → This broker is currently the active controller.\nValue is 0 → This broker is not the active controller.\nThis Values should not be 0 or more tha  1 for longer period of time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"fpe-tools-stg\", instance=~\"$instance\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Total number of network requests per second",
   "type": "timeseries",
   "description": "This metric measures the total number of network requests per second received by a Kafka broker.\nThis metric helps monitor:\nLoad on each Kafka broker (number of client requests)\nThroughput patterns over time\nSudden spikes or drops, which could indicate client issues, network problems, or overload",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_network_requestmetrics_requestspersec_count{namespace=\"fpe-tools-stg\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}