{
 "title": "Apisix Resource Utilization Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "APISIX Pod Working Set Memory (MiB)",
   "type": "timeseries",
   "description": "Displays the working set memory (in MiB) of APISIX pods in the fpe-tools-stg namespace. This metric reflects the actual memory actively used by the application, excluding cache and reclaimable memory. It’s a more accurate measure of memory pressure than total usage, helping identify real memory bottlenecks or leaks in production.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"apisix-.*\"} / (1024 * 1024)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "APISIX Pod CPU Usage (5m Rate)",
   "type": "timeseries",
   "description": "This panel shows the average CPU usage per second (in cores) for each APISIX pod, calculated over the last 5 minutes using rate(container_cpu_usage_seconds_total[5m]).\nIt helps monitor real-time CPU demand and identify pods consuming excessive CPU.\nValues are displayed in core units, where 1.0 equals one full CPU core usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{pod=~\"apisix-.*\"}[5m])\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APISIX Pod Network Outbound Rate (5m)",
   "type": "timeseries",
   "description": "This panel shows the rate of outbound network traffic (in bytes per second) sent from each APISIX pod over the past 5 minutes.\nIt uses the Prometheus metric rate(container_network_transmit_bytes_total{pod=~\"apisix-.*\"}[5m]), which helps track how much data each pod is sending.\nUseful for identifying service egress patterns, potential congestion, or data exfiltration issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"apisix-.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APISIX Pod Network Inbound Rate (5m)",
   "type": "timeseries",
   "description": "This panel displays the rate of inbound network traffic (in bytes per second) received by each APISIX pod over a 5-minute interval.\nIt uses the Prometheus metric rate(container_network_receive_bytes_total{pod=~\"apisix-.*\"}[5m]), which measures how fast data is being received.\nUseful for detecting unusual inbound traffic patterns, load spikes, or network bottlenecks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"apisix-.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current memory usage (in MiB)",
   "type": "timeseries",
   "description": "Displays real-time memory usage (in MiB) of all running APISIX pods in the fpe-tools-stg namespace. Useful for monitoring pod memory consumption and detecting memory leaks or spikes due to traffic/load or plugin usage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"apisix-.*\", namespace=\"fpe-tools-stg\"} / (1024 * 1024)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "APISIX Pod Filesystem Write Rate (5m)",
   "type": "timeseries",
   "description": "This panel shows the rate of filesystem write operations (in bytes per second) by each APISIX pod over the last 5 minutes.\nIt uses the Prometheus query:\nrate(container_fs_writes_bytes_total{pod=~\"apisix-.*\"}[5m])\nThis helps monitor disk I/O write activity to detect excessive disk usage or potential performance bottlenecks in APISIX pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{pod=~\"apisix-.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APISIX Pod Filesystem Read Rate (5m)",
   "type": "timeseries",
   "description": "This panel displays the rate of filesystem read operations (in bytes per second) by each APISIX pod, averaged over the past 5 minutes.\nIt uses the Prometheus metric rate(container_fs_reads_bytes_total{pod=~\"apisix-.*\"}[5m]).\nThis helps in monitoring disk I/O read activity and identifying any pods performing unusually high read operations which could impact performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{pod=~\"apisix-.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}