{
 "title": "Apisix dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Latency Distribution by Route",
   "type": "timeseries",
   "description": "This panel displays the rate of requests grouped by latency buckets (e.g., <50ms, <100ms, etc.) for each route in APISIX over the last 30 minutes. It helps in monitoring and identifying the latency performance across different routes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_latency_bucket[30m])) by (le, route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of HTTP responses grouped by route",
   "type": "timeseries",
   "description": "This query will return the total number of responses grouped by routes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(apisix_http_status_total) by (route)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency for Specific Route",
   "type": "timeseries",
   "description": "This gives the latency grouped by route. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(apisix_http_latency_sum) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency per request by Route",
   "type": "timeseries",
   "description": "This gives you average latency per request grouped by route.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(apisix_http_latency_sum[30m])) by (route) \r\n/ \r\navg(rate(apisix_http_latency_count[30m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total Request Count per Route",
   "type": "timeseries",
   "description": "This gives the total request count based on each route",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_latency_count[1h])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Latency per Route (10m Window)",
   "type": "timeseries",
   "description": "This panel shows the 95th percentile of request latency per route over a rolling 10-minute window. High values may indicate performance degradation or bottlenecks in specific API routes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket[10m])) by (le, route))\r\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP responses by status code",
   "type": "timeseries",
   "description": "his query will return the total number of responses grouped by HTTP status codes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(apisix_http_status_total[10m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted or Handled requests",
   "type": "timeseries",
   "description": "apisix_nginx_http_current_connections\nThis is the metric that tracks the current number of HTTP connections in APISIX. {state=~\"accepted|handled\"}\nThis part uses a regular expression (regex) filter on the state label. The regex \"accepted|handled\" means \"match if the label value is either accepted or handled.\" It will return data points for both the accepted state and the handled state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "apisix_nginx_http_current_connections{state=~\"accepted|handled\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Trend (Time Series)",
   "type": "timeseries",
   "description": "To visualize the latency sum over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(apisix_http_latency_sum[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apisix HTTP QPS",
   "type": "timeseries",
   "description": "apisix_http_requests_total This is a counter metric that typically increases over time, representing the total number of HTTP requests processed by APISIX. The rate() function calculates the per-second average increase of the counter over the specified time range. This panel shows us the average number of HTTP requests that have been processed per second over the last 5 minutes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {},
    {
     "expr": "rate(apisix_http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Modify Index for each Key",
   "type": "timeseries",
   "description": "A modify index is a versioning mechanism that tracks changes made to a particular key. This will return the highest modify index for each key.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max(apisix_etcd_modify_indexes) by (key)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation ",
   "type": "timeseries",
   "description": "apisix_shared_dict_capacity_bytes is Total allocated memory size.\n\napisix_shared_dict_free_space_bytes is Free (unused) memory in that dictionary.\n1 - (free / capacity) gives the fraction used.\nThis gives you the percentage of used memory in APISIX's shared memory dictionary to monitor memory usage in shared dicts. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "(1 - (apisix_shared_dict_free_space_bytes / apisix_shared_dict_capacity_bytes))*100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current HTTP connections grouped by their state",
   "type": "timeseries",
   "description": "This query will return the total number of active HTTP connections grouped by their state\nactive: Connections that are currently active.\n\nreading: Connections where the server is reading the request header.\n\nwriting: Connections where the server is writing the response back to the client.\n\nwaiting: Idle connections waiting for a reque",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(apisix_nginx_http_current_connections) by (state)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active HTTP Connections",
   "type": "timeseries",
   "description": "apisix_nginx_http_current_connections indicates the number of current HTTP connections managed by APISIX's Nginx component. The label selector {state=\"active\"} filters the metric to only include data points that have the label state with the value \"active\". The result of this query shows you the current number of active HTTP connections managed by the APISIX instance's Nginx. This is useful for monitoring the load on your system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "apisix_nginx_http_current_connections{state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Throughput (RPS)",
   "type": "timeseries",
   "description": "Shows Requests per Second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(apisix_http_latency_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress Bandwidth (Outflow)",
   "type": "timeseries",
   "description": "This query gives you the total egress bandwidth over a 5-minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth_total{type=\"egress\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Etcd Reachability",
   "type": "timeseries",
   "description": "apisix_etcd_reachable indicates whether APISIX is successfully able to reach its etcd backend. Likely returns 1 when etcd is reachable.\n\nReturns 0 (or otherwise signals failure) when etcd is unreachable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "apisix_etcd_reachable", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ingress Bandwidth",
   "type": "timeseries",
   "description": "This query gives you the total ingress bandwidth over a 5-minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(rate(apisix_bandwidth_total{type=\"ingress\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error     ",
   "type": "timeseries",
   "description": "apisix_nginx_metric_errors_total counts the total number of errors encountered while collecting or processing Nginx metrics in APISIX.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "apisix_nginx_metric_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "(rate(apisix_nginx_metric_errors_total[5m]) / rate(apisix_http_requests_total[5m]))\n\nIt calculates the fraction of HTTP requests that resulted in errors, by dividing the error rate by the request rate over a 5-minute interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "(rate(apisix_nginx_metric_errors_total[5m]) / rate(apisix_http_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apisix Node Info ",
   "type": "timeseries",
   "description": "This panel is used to display which nodes are running APISIX, what version they’re using, and other identifying metadata.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "apisix_node_info", "legendFormat": "__auto" }
   ]
  }
 ]
}