{
 "title": "Data Services / Apache Spark - Performance Metrics",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "tags": [
  "data-services",
  "spark"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"fpe-tools-(stg)\"},namespace)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$Pod\"}, pod)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "query_result(kube_pod_status_phase{pod=\"$Pod\"})"
    }
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name=~\"$Pod\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver IP Address",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "Pod",
   "options": { "content": "# $Pod_ip" }
  },
  {
   "title": "Driver Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "repeat": "Pod",
   "options": { "content": "# $phase" }
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{pod=~\"^$Pod$\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$Pod$\",namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  { "title": "Driver Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Driver Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum (container_memory_working_set_bytes{pod=~\"^$Pod$\",namespace=\"$namespace\"}) /sum (container_memory_usage_bytes{pod=~\"^$Pod$\",namespace=\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Executor Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum (container_memory_working_set_bytes{pod=~\"^$executor$\",namespace=\"$namespace\"}) /sum (container_memory_usage_bytes{pod=~\"^$executor$\",namespace=\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$executor$\",namespace=\"$namespace\"})"
    }
   ]
  },
  { "title": "Driver CPU / Memory  usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Driver Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "Pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{pod=\"$Pod\",namespace=\"$namespace\"}[2m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Driver CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "CPU Time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$Pod$\",namespace=\"$namespace\"} [2m])) by (pod) ",
     "legendFormat": "Used CPU : {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Driver GC : Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{pod=~\"$Pod\",gc=\"Copy\",namespace=\"$namespace\"}",
     "legendFormat": "{{ gc }}"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{pod=~\"$Pod\",gc=\"MarkSweepCompact\",namespace=\"$namespace\"}",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  { "title": "Executor CPU /Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Executor :  Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{pod=~\"$executor\",namespace=\"$namespace\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Executor  :  CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "CPU Time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$executor\",namespace=\"$namespace\"} [4m])) by (pod) ",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Executor GC : Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{pod=~\"$executor\",gc=\"Copy\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }} {{ gc }}"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{pod=~\"$executor\",gc=\"MarkSweepCompact\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }} {{ gc }}"
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Driver Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$Pod',namespace=\"$namespace\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$Pod',namespace=\"$namespace\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$executor',namespace=\"$namespace\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }} {{ node }} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$executor',pod!=\"pod\",namespace=\"$namespace\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }} {{ node }}  Received"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$Pod|$executor\",device=~\"/dev/sd[a|c|e]\",namespace=\"$namespace\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }} {{ device }} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$Pod|$executor\",device=~\"/dev/sd[a|c|e]\",namespace=\"$namespace\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }} {{ device }} Write"
    }
   ]
  },
  { "title": "Spark External Shuffle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Spark Shuffle Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'.*shuffle.*',namespace=\"$namespace\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }} {{ node }} Transmitted"
    }
   ]
  },
  {
   "title": "Spark Shuffle Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_shuffletotalbytesread_type_counters_count{pod=~\"^$executor$\",namespace=\"$namespace\"})",
     "legendFormat": "{{ pod }} {{ node }}  Received"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_shuffletotalbytesread_type_counters_count{pod=~\"^$executor$\",namespace=\"$namespace\"})",
     "legendFormat": "{{ pod }} {{ device }} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_shufflebyteswritten_type_counters_count{pod=~\"^$executor$\",namespace=\"$namespace\"})",
     "legendFormat": "{{ pod }} {{ device }} Write"
    }
   ]
  },
  { "title": "Memory Heap / Non - Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod=~\"^$Pod$\",area=\"heap\",namespace=\"$namespace\"} ",
     "legendFormat": "{{ pod }} "
    },
    {
     "expr": "jvm_memory_bytes_used{pod=~\"^$executor$\",area=\"heap\",namespace=\"$namespace\"}",
     "legendFormat": " {{ pod }} "
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod=~\"$Pod\",area=\"nonheap\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "jvm_memory_bytes_used{pod=~\"$executor\",area=\"nonheap\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "JVM Threads & Memory Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Memory Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pod=~\"$executor\",namespace=\"$namespace\"}) by (pod,pool)",
     "legendFormat": "{{ pod }} {{ pool }}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pod=~\"$Pod\",namespace=\"$namespace\"}) by (name,pool)",
     "legendFormat": "{{ pod }} {{ pool }}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_current{pod=~\"$executor\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {
     "expr": "sum(jvm_threads_current{pod=~\"$Pod\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Executor : Completed Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "spark_executor_succeededtasks_type_counters_count{pod=~\"$executor\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    },
    {}
   ]
  },
  {
   "title": "Executor : Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "spark_executor_executor_threadpool_activetasks{pod=~\"$executor\",namespace=\"$namespace\"}",
     "legendFormat": "{{pod }}"
    },
    {}
   ]
  },
  { "title": "Miscellaneous Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Executors Spawned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_name=~\"$Pod\",namespace=\"$namespace\"})",
     "legendFormat": "Executor Counts "
    }
   ]
  },
  {
   "title": "Packets Dropped : Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total{pod=~\"$Pod|$executor\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod_name }} - Receive"
    },
    {
     "expr": "container_network_transmit_packets_dropped_total{pod=~\"$Pod|$executor\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod_name }} - Transmit"
    }
   ]
  },
  {
   "title": "Kubernetes Pod Slice",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 89 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{pod=~\"$executor\",namespace=\"$namespace\"}"
    },
    {
     "expr": "container_network_receive_bytes_total{pod=~\"$Pod\",namespace=\"$namespace\"}"
    },
    {}
   ]
  }
 ]
}