{
 "title": "Data Services / Kafka Health Monitoring",
 "description": "Monitors kafka-health metrics using Prometheus in Kubernetes",
 "tags": [
  "kafka",
  "data-services"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=~\"fpe-tools-(stg)\"},namespace)"
    }
   },
   {
    "name": "servicename",
    "label": "Kafka Cluster Name",
    "query": {
     "query": "label_values(kafka_brokers{app_kubernetes_io_instance=~\".*.*\", namespace=\"$namespace\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\",app_kubernetes_io_instance='$servicename'}, instance)"
    }
   },
   {
    "name": "topicname",
    "label": "Kafka Topic Name",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{app_kubernetes_io_instance='$servicename',topic!='__consumer_offsets',topic!='--kafka',namespace=\"$namespace\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System health (Broker)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(max(kafka_server_replicamanager_total_partitioncount_value{app_kubernetes_io_instance=\"$servicename\",namespace=\"$namespace\"})by(instance))"
    }
   ]
  },
  {
   "title": "Produced",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_totalproducerequestspersec_oneminuterate{ namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance) - sum(kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "{{ instance }} Successful Requests"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "{{ instance }} Failed Requests"
    }
   ]
  },
  {
   "title": "Fetched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_totalfetchrequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance) - sum(kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "{{ instance }} Successful Requests"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "{{ instance }} Failed Requests"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "A number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "floor(sum(kafka_controller_kafkacontroller_activecontrollercount_value{ namespace=\"$namespace\", app_kubernetes_io_instance=~\"$servicename\"}))"
    }
   ]
  },
  {
   "title": "Unclean elections",
   "type": "stat",
   "description": "Unclean leader election rate.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance)"
    }
   ]
  },
  {
   "title": "Network pool usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(100*(1-avg(kafka_network_processor_idlepercent_value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})))"
    }
   ]
  },
  {
   "title": "Isr Expansion / Shrink Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_isrexpandspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "{{ instance }} Expand"
    },
    {
     "expr": "-sum(kafka_server_replicamanager_total_isrshrinkspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "{{ instance }} Shrink"
    }
   ]
  },
  {
   "title": "Request pool usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(100*(1-avg(kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{ namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})))"
    }
   ]
  },
  {
   "title": "Online Topic Partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount_value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})"
    }
   ]
  },
  {
   "title": "Broker State",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 20, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(instance)",
     "legendFormat": "Bytes in/sec"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesoutpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(instance)",
     "legendFormat": "Bytes out/sec"
    },
    {
     "expr": "max(kafka_server_replicamanager_total_partitioncount_value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(instance)"
    },
    {
     "expr": "sum(kafka_log_log_size{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(instance)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated Partitions (| Isr | < | all replicas |). Alert if value is greater than 0.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$servicename\"})by(app_kubernetes_io_instance)"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Number of Partitions that don't have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$servicename\"})"
    }
   ]
  },
  {
   "title": "Bytes in Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesoutpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "System health (Topics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Topic Count",
   "type": "stat",
   "description": "Aggregate incoming byte rate",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kafka_topic_partition_replicas{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(topic)) - 1"
    }
   ]
  },
  {
   "title": "Produced",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 35 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_totalproducerequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance) - sum(kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_failedproducerequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})by(app_kubernetes_io_instance, instance)",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Fetched",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_totalfetchrequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"}) - sum(kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_failedfetchrequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "In sync replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_in_sync_replica{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})"
    }
   ]
  },
  {
   "title": "Topic State",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 41 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesoutpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_topic_partition_replicas{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_topic_partition_replicas{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)-sum(kafka_topic_partition_in_sync_replica{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\", topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_log_log_numlogsegments{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_log_log_size{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic) / sum(kafka_log_log_numlogsegments{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_log_log_size{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "max(kafka_log_log_logstartoffset{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "max(kafka_log_log_logendoffset{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic)"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic) / sum(kafka_server_brokertopicmetrics_total_totalproducerequestspersec_oneminuterate{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\",topic=~\"$topicname\"})by(topic)"
    }
   ]
  },
  {
   "title": "Out of sync replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_replicas{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})-count(kafka_topic_partition_in_sync_replica{namespace=\"$namespace\", app_kubernetes_io_instance=\"$servicename\"})"
    }
   ]
  }
 ]
}