{
 "title": "Data Services / Kafka Stream Monitoring",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "kafka",
  "data-services"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_brokers{namespace=~\"fpe-tools-(stg)\"}, service)"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_lag{service='$instance',consumergroup!~\"_.*\"}, consumergroup)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{service='$instance',topic!='__consumer_offsets',topic!='--kafka', topic!~\"_.*\"}, topic)"
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": "label_values(kafka_topic_partition_current_offset{service='$instance',topic!='__consumer_offsets',topic!='--kafka', topic!~\"_.*\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Offset Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Group Offset Overview",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"})by(consumergroup)"
      },
      {
       "expr": "min(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"})by(consumergroup)"
      },
      {
       "expr": "max(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"})by(consumergroup) - min(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"})by(consumergroup)"
      },
      {
       "expr": "sum(bottomk by(consumergroup)(1, kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"}))by(consumergroup, partition)"
      }
     ]
    },
    {
     "title": "Average Offset by Consumer Group",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"})by(consumergroup)",
       "legendFormat": "{{ consumergroup }}"
      }
     ]
    },
    {
     "title": "Consumer Group Offset (Consumer Group, Topic, Partition)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"})by(consumergroup, partition, topic)",
       "legendFormat": " ({{ consumergroup }}, {{ topic }}, {{ partition }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Group Message Rate Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Group Message Rate Overview",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\", topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)"
      },
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{service=~'$instance', topic=~\"$topic\", topic!~\"dcos.*\"}[5m])/5) by (topic)"
      }
     ]
    },
    {
     "title": "Partion Message Summary",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{service=~'$instance', consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"}[5m])/5) by (partition, topic)"
      },
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{service=~'$instance', topic=~\"$topic\", topic!~\"dcos.*\"}[5m])/5) by (topic)"
      }
     ]
    },
    {
     "title": "Messages in per Minute by Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{service=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Messages Consumed Per Minute by Consumer Group",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\"}[5m])/5) by (consumergroup)",
       "legendFormat": "{{ consumergroup }}"
      }
     ]
    },
    {
     "title": "Topic Messages Per Min Consumer Group Consumes (Consumer Group - Topic)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\", topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
       "legendFormat": "{{ consumergroup }} - {{ topic }}"
      }
     ]
    },
    {
     "title": "Topic Messages Consumed Per Minute by Consumer Group and Partition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{service=~'$instance',consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"}[5m])/5) by (consumergroup, topic, partition)",
       "legendFormat": " ({{ consumergroup }}, {{ partition }}) -  {{ topic }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lag Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag by Consumer Group",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{service=~\"$instance\",consumergroup=~\"$consumergroup\"}) by (consumergroup) ",
       "legendFormat": "{{ consumergroup }}"
      }
     ]
    },
    {
     "title": "Lag by Consumer Group & Topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{service=~\"$instance\",consumergroup=~\"$consumergroup\", topic=~\"$topic\"}) by (consumergroup, topic) ",
       "legendFormat": "{{consumergroup}}, {{topic}}"
      }
     ]
    },
    {
     "title": "Lag by Consumer Group, Topic, and Partition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_consumergroup_lag{service=~\"$instance\",consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"})by(partition, topic, consumergroup)",
       "legendFormat": "{{ consumergroup }},    {{ topic }},     {{ partition }}"
      }
     ]
    },
    {
     "title": "Consumer Group Lag Summary",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "avg(kafka_consumergroup_lag{service=~\"$instance\",consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"})by(topic, partition, consumergroup)"
      }
     ]
    },
    {
     "title": "Consumer Group Lag and Offset Metircs",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_current_offset{consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"})by(consumergroup, topic, partition)"
      },
      {
       "expr": "sum(kafka_topic_partition_current_offset{topic=~\"$topic\", partition=~\"$partition\"})by(topic, partition)"
      },
      {
       "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"$consumergroup\", topic=~\"$topic\", partition=~\"$partition\"})by(consumergroup, topic, partition)"
      },
      {
       "expr": "min(kafka_log_log_logendoffset{topic=~\"$topic\"})by(topic)"
      },
      {
       "expr": "max(kafka_log_log_logendoffset{topic=~\"$topic\"})by(topic)"
      }
     ]
    }
   ]
  },
  { "title": "Partition Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Topic to Partition Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(sum(kafka_topic_partition_current_offset{service=~\"$instance\", topic=~\"$topic\"})by(partition, topic))by(topic)"
    }
   ]
  },
  {
   "title": "Partion to Topic Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count(sum(kafka_topic_partition_current_offset{service=~\"$instance\", topic=~\"$topic\"})by(partition, topic))by(partition)"
    }
   ]
  }
 ]
}