{
 "title": "Kubernetes Namespace ResourceQuota",
 "description": "Display usage of ResourceQuota by namespace in kubernetes cluster. ",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_resourcequota{exported_namespace=~\"fpe-tools-(stg)\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Allocated / Requests Quota (CPU)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Limits Allocated / Limits Quota (CPU)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actual Usage / Request Quota (CPU)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) / sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actual Usage / Limits Quota (CPU)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests Allocated / Requests Quota (Memory)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Limits Allocated / Limits Quota (Memory)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actual Usage / Request Quota (Memory)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actual Usage / Limits Quota (Memory)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests Allocated / Requests Quota (Storage)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"requests.storage\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.storage\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Limits Allocated / Limits Quota (Storage)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_resourcequota{resource=\"limits.storage\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.storage\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actual Usage / Request Quota (Storage)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"requests.storage\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Actual Usage / Limits Quota (Storage)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.storage\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.cpu\", type=\"hard\"}",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.cpu\", type=\"hard\"}",
     "legendFormat": "CPU Quota Requests"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.cpu\", type=\"used\"}",
     "legendFormat": "CPU Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.cpu\", type=\"used\"}",
     "legendFormat": "CPU Allocated Requests"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=\"$namespace\"})",
     "legendFormat": "Actual Usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.memory\", type=\"hard\"}",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.memory\", type=\"hard\"}",
     "legendFormat": "Memory Quota Requests"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.memory\", type=\"used\"}",
     "legendFormat": "Memory Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.memory\", type=\"used\"}",
     "legendFormat": "Memory Allocated Requests"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "description": "This represents the total [Storage resource requests](https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota) is also shown.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "Storage" }
   ],
   "targets": [
    {
     "expr": "sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Actual Usage"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.storage\", type=\"hard\"}",
     "legendFormat": "Storage Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.storage\", type=\"hard\"}",
     "legendFormat": "Storage Requests"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"limits.storage\", type=\"used\"}",
     "legendFormat": "Storage Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", resource=\"requests.storage\", type=\"used\"}",
     "legendFormat": "Storage Allocated Requests"
    }
   ]
  }
 ]
}