{
 "title": "Ops dashboard sample",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes Namespace Resource Alerts (CPU, Memory, PVC) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Namespace CPU Usage ",
   "type": "timeseries",
   "description": "Shows namespaces using >50% of CPU request — trend tracking. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\",namespace!=\"\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage  ",
   "type": "timeseries",
   "description": "Shows memory usage >50% of request across namespaces. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",namespace!=\"\"}) by (namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace PVC Usage  ",
   "type": "timeseries",
   "description": "Tracks PVC usage trends over time — see growth patterns. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace!=\"\"}) / sum(kubelet_volume_stats_capacity_bytes{namespace!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}